// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"database/sql"
	"time"
)

type DifficultyLevel struct {
	ID   string `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type Problem struct {
	ID           int64     `db:"id" json:"id"`
	Slug         string    `db:"slug" json:"slug"`
	Title        string    `db:"title" json:"title"`
	Url          string    `db:"url" json:"url"`
	Duration     int64     `db:"duration" json:"duration"`
	DifficultyID string    `db:"difficulty_id" json:"difficulty_id"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type ProblemTopic struct {
	ProblemID int64  `db:"problem_id" json:"problem_id"`
	TopicID   string `db:"topic_id" json:"topic_id"`
}

type Reminder struct {
	ID         int64     `db:"id" json:"id"`
	LastSentAt time.Time `db:"last_sent_at" json:"last_sent_at"`
	Type       string    `db:"type" json:"type"`
}

type Review struct {
	ID         int64          `db:"id" json:"id"`
	ProblemID  int64          `db:"problem_id" json:"problem_id"`
	ReviewDate time.Time      `db:"review_date" json:"review_date"`
	Completed  bool           `db:"completed" json:"completed"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	Notes      sql.NullString `db:"notes" json:"notes"`
}

type Topic struct {
	ID   string `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

type UserProgress struct {
	ProblemID       int64        `db:"problem_id" json:"problem_id"`
	Status          string       `db:"status" json:"status"`
	LastAttemptedAt sql.NullTime `db:"last_attempted_at" json:"last_attempted_at"`
	Attempts        int64        `db:"attempts" json:"attempts"`
	CreatedAt       time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time    `db:"updated_at" json:"updated_at"`
}
